version: '3.8'

services:
  zurg:
    image: ghcr.io/debridmediamanager/zurg-testing:latest    
    container_name: zurg
    restart: unless-stopped
    ports:
      - 9999:9999
    environment:
      TZ: Asia/Kolkata
      PUID: 0
      PGID: 0
    volumes:
      - ./plex_update.sh:/app/plex_update.sh
      - ./config.yml:/app/config.yml
      - zurgdata:/app/data

  rclone:
    image: rclone/rclone:latest
    container_name: rclone
    restart: unless-stopped
    environment:
      TZ: Asia/Kolkata
      PUID: 0
      PGID: 0
    volumes:
      - /mnt/zurg:/data:rshared # CHANGE /mnt/zurg WITH YOUR PREFERRED MOUNT PATH
      - /mnt/zurg-testing/rclone.conf:/config/rclone/rclone.conf
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    depends_on:
      - zurg
    command: "mount zurg: /data --allow-other --allow-non-empty --dir-cache-time=5s --buffer-size=64M --poll-interval=15s --use-mmap --vfs-read-ahead=128M --vfs-read-chunk-size=64M --vfs-read-chunk-size-limit=2048M --vfs-cache-max-age=48h --vfs-cache-mode=full --vfs-cache-poll-interval=30s --vfs-cache-max-size=10G --cache-dir=/mnt/cache"

volumes:
  zurgdata:
